name: mediapipe
channels:
  - anaconda
  - conda-forge
  - auto 
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipython
  - pillow
  - h5py
  - seaborn
  - pandas
  - cython
  - numexpr
  - appdirs
  - scikit-learn
  - scikit-image
  - shapely
  - opencv
  - python-wget
  - pip
  - pypng  
  - pip:
    - mediapipe
    - imageio-ffmpeg
